# Generated by Django 2.2 on 2019-08-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190826_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividend',
            name='month_int',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
