# Generated by Django 2.2 on 2019-08-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dividend_month_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividend',
            name='month',
            field=models.IntegerField(blank=True, choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')], null=True),
        ),
    ]
