# Generated by Django 2.2 on 2019-08-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190826_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='percentage_difference_between_dividend_income_wanted',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='percentage_of_estimated_income_reached',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
