# Generated by Django 2.2 on 2019-08-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='urltoimage',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
