# Generated by Django 2.2 on 2019-09-09 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190906_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmember',
            old_name='stock',
            new_name='group',
        ),
    ]
