# Generated by Django 2.2 on 2019-09-09 05:12

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190908_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='contents',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default='Content Here!'),
            preserve_default=False,
        ),
    ]
