# Generated by Django 2.2.5 on 2019-09-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190908_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='published',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
