# Generated by Django 2.2.5 on 2019-10-09 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_comments_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='repost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Post'),
        ),
    ]
