# Generated by Django 2.2.5 on 2019-10-14 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20191012_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='moderator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.GenGroup'),
        ),
    ]
