# Generated by Django 2.2.5 on 2019-10-17 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20191013_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='online_status',
            field=models.CharField(blank=True, choices=[('o', 'online'), ('g', 'in group'), ('f', 'offline')], default='f', max_length=1, null=True),
        ),
    ]
