# Generated by Django 2.2.5 on 2019-10-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_user_profile_online_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='group_online_status',
            field=models.CharField(blank=True, choices=[('o', 'online'), ('f', 'offline')], default='f', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='online_status',
            field=models.CharField(blank=True, choices=[('o', 'online'), ('f', 'offline')], default='f', max_length=1, null=True),
        ),
    ]
