# Generated by Django 2.2.5 on 2019-10-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20191016_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='creator',
            field=models.BooleanField(default=False),
        ),
    ]
