# Generated by Django 2.2.5 on 2019-10-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_groupmember_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='member_status',
            field=models.CharField(blank=True, choices=[('m', 'Member'), ('a', 'Admin'), ('d', 'Moderator')], default='m', max_length=1, null=True),
        ),
    ]
