# Generated by Django 2.2.5 on 2019-11-01 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20191031_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreplyarchive',
            name='userprofile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.User_Profile'),
        ),
        migrations.AddField(
            model_name='commentsarchive',
            name='userprofile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.User_Profile'),
        ),
        migrations.AddField(
            model_name='postarchive',
            name='userprofile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.User_Profile'),
        ),
    ]
