# Generated by Django 2.2.5 on 2019-11-01 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20191031_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreplyarchive',
            name='userprofile',
        ),
        migrations.RemoveField(
            model_name='commentsarchive',
            name='userprofile',
        ),
        migrations.RemoveField(
            model_name='postarchive',
            name='userprofile',
        ),
    ]
