# Generated by Django 2.2.5 on 2019-11-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20191031_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='post_recipients', to='core.User_Profile'),
        ),
    ]
