# Generated by Django 2.2.5 on 2019-11-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_post_recipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='postrecipients', to='core.User_Profile'),
        ),
    ]
