# Generated by Django 2.2.5 on 2019-11-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20191104_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='stock',
        ),
        migrations.AddField(
            model_name='commentreply',
            name='stocks',
            field=models.ManyToManyField(blank=True, to='core.Stocks'),
        ),
        migrations.AddField(
            model_name='comments',
            name='stocks',
            field=models.ManyToManyField(blank=True, to='core.Stocks'),
        ),
    ]
