# Generated by Django 2.2.5 on 2019-11-08 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_post_post_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_picture',
        ),
    ]
