# Generated by Django 2.2.5 on 2019-11-10 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_postpicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_picture', models.ImageField(blank=True, null=True, upload_to='comments_img/')),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Comments')),
            ],
        ),
        migrations.CreateModel(
            name='CommentReplyPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentreply_picture', models.ImageField(blank=True, null=True, upload_to='commentreply_img/')),
                ('commentreply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CommentReply')),
            ],
        ),
    ]
