# Generated by Django 2.2.5 on 2019-11-20 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_commentreplypicture_commentspicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockWatchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated', models.DateField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User_Profile')),
            ],
        ),
        migrations.CreateModel(
            name='WatchStockDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Stocks')),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.StockWatchlist')),
            ],
        ),
        migrations.AddField(
            model_name='stockwatchlist',
            name='stocks',
            field=models.ManyToManyField(blank=True, through='core.WatchStockDetail', to='core.Stocks'),
        ),
        migrations.CreateModel(
            name='GroupWatchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GenGroup')),
                ('stockwatchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.StockWatchlist')),
            ],
        ),
        migrations.AddField(
            model_name='gengroup',
            name='stock_watchlist',
            field=models.ManyToManyField(blank=True, through='core.GroupWatchlist', to='core.StockWatchlist'),
        ),
    ]
