# Generated by Django 2.2.5 on 2019-11-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20191119_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockwatchlist',
            name='downloaded',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
