# Generated by Django 2.2.5 on 2019-11-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_stockwatchlist_downloaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockwatchlist',
            name='downloaded',
            field=models.IntegerField(default=0),
        ),
    ]
