# Generated by Django 2.2.5 on 2019-11-28 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20191127_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User_Profile')),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.StockWatchlist')),
            ],
        ),
        migrations.AddField(
            model_name='stockwatchlist',
            name='downloader',
            field=models.ManyToManyField(blank=True, related_name='downloadee', through='core.WatchlistDownload', to='core.User_Profile'),
        ),
    ]
