# Generated by Django 2.2.5 on 2019-12-08 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20191127_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='groupfiles/')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated', models.DateField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('downloadedf', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User_Profile')),
            ],
        ),
        migrations.CreateModel(
            name='GroupFileList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.File')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GenGroup')),
            ],
        ),
        migrations.CreateModel(
            name='FileDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaderf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User_Profile')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.File')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='downloaderf',
            field=models.ManyToManyField(blank=True, related_name='downloadeef', through='core.FileDownload', to='core.User_Profile'),
        ),
        migrations.AddField(
            model_name='gengroup',
            name='files',
            field=models.ManyToManyField(blank=True, through='core.GroupFileList', to='core.File'),
        ),
    ]
