# Generated by Django 2.2.5 on 2019-12-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20191207_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='alert',
            field=models.BooleanField(default=False),
        ),
    ]
