# Generated by Django 2.2.5 on 2019-12-10 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_post_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Post')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.WebsiteUrl')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='attached_url',
            field=models.ManyToManyField(blank=True, through='core.PostUrl', to='core.WebsiteUrl'),
        ),
    ]
