# Generated by Django 2.2.5 on 2019-12-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_groupmember_timespent_in_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='avg_session_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
