# Generated by Django 2.2.5 on 2019-12-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_groupmember_avg_session_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='in_group_time',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
