# Generated by Django 2.2.5 on 2019-12-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_notification_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
