# Generated by Django 2.2.5 on 2019-12-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_user_profile_notification_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='post_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
