# Generated by Django 2.2.5 on 2019-12-16 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_notification_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DividendWealthMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('membership_type', models.CharField(blank=True, choices=[('f', 'Free'), ('m', 'Monthly'), ('y', 'Year'), ('l', 'Lifetime')], default='f', max_length=1, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('stripe_plan_id', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user_profile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='dividend_wealth_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DividendWealthMembership'),
        ),
    ]
