# Generated by Django 2.2.5 on 2019-12-16 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_auto_20191216_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dividendwealthmembership',
            old_name='membership_type',
            new_name='membership',
        ),
    ]
