# Generated by Django 2.2.5 on 2019-12-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20191216_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividendwealthmembership',
            name='membership',
            field=models.CharField(blank=True, choices=[('f', 'Free'), ('m', 'Monthly'), ('y', 'Yearly'), ('l', 'Lifetime')], default='f', max_length=1, null=True),
        ),
    ]
