# Generated by Django 2.2.5 on 2019-12-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_dividendwealthfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividendwealthmembership',
            name='subscription',
            field=models.BooleanField(default=True),
        ),
    ]
