# Generated by Django 2.2.5 on 2019-12-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_auto_20191225_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='stripe_user_buisness_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
