# Generated by Django 2.2.5 on 2019-12-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_user_profile_stripe_user_buisness_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='stripe_connected_account_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
