# Generated by Django 2.2.5 on 2019-12-31 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_auto_20191229_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividendwealthconnectedaccount',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='DividendWealthConnectedAccountPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='core.User_Profile')),
                ('connected_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DividendWealthConnectedAccount')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User_Profile')),
            ],
        ),
    ]
