# Generated by Django 2.2.5 on 2020-01-03 04:45

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_auto_20191230_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='gengroup',
            name='rules_guidlines',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gengroup',
            name='value_proposition',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
