# Generated by Django 2.2.5 on 2020-01-03 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_auto_20200102_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='gengroup',
            name='group_picture',
            field=models.ImageField(blank=True, null=True, upload_to='group-pics/'),
        ),
        migrations.AddField(
            model_name='gengroup',
            name='group_type',
            field=models.CharField(blank=True, choices=[('f', 'Free'), ('s', 'Subscription'), ('o', 'One Time Fee')], default='f', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='gengroup',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GroupCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Categories')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GenGroup')),
            ],
        ),
        migrations.AddField(
            model_name='gengroup',
            name='catagories',
            field=models.ManyToManyField(blank=True, through='core.GroupCategories', to='core.Categories'),
        ),
    ]
