# Generated by Django 2.2.5 on 2020-01-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_auto_20200102_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gengroup',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
