# Generated by Django 2.2.5 on 2020-01-06 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_auto_20200104_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_posts_today', models.IntegerField(blank=True, null=True)),
                ('posts_this_month', models.IntegerField(blank=True, null=True)),
                ('avg_num_members_online', models.IntegerField(blank=True, null=True)),
                ('avg_mem_joining_week', models.IntegerField(blank=True, null=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.GenGroup')),
            ],
        ),
    ]
