# Generated by Django 2.2.5 on 2020-01-07 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_grouppayment_groupsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppayment',
            name='charge_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='groupsubscription',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.GenGroup'),
        ),
        migrations.AlterField(
            model_name='grouppayment',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.GenGroup'),
        ),
    ]
