# Generated by Django 2.2.5 on 2020-01-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_auto_20200106_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsubscription',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
