# Generated by Django 2.2.5 on 2020-01-08 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_groupsubscription_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='gengroup',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
