# Generated by Django 2.2.5 on 2020-01-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_gengroup_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='gengroup',
            name='connected_member',
            field=models.BooleanField(default=False),
        ),
    ]
