# Generated by Django 2.2.5 on 2020-01-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_gengroup_connected_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gengroup',
            name='connected_member',
        ),
        migrations.AddField(
            model_name='gengroup',
            name='unpublished_reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
