# Generated by Django 2.2.5 on 2020-01-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_auto_20200112_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
