# Generated by Django 2.2.5 on 2020-02-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_groupmember_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
