# Generated by Django 2.2.5 on 2020-02-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_auto_20200215_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='groupfiles/'),
        ),
    ]
