# Generated by Django 2.2.5 on 2020-02-24 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_auto_20200223_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gengroup',
            old_name='catagories',
            new_name='categories',
        ),
    ]
