# Generated by Django 2.2.5 on 2020-02-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_auto_20200223_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='query_cat',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
