# Generated by Django 2.2.5 on 2020-03-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_article_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='background_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_background_img/'),
        ),
    ]
