# Generated by Django 2.2.5 on 2020-03-06 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_user_profile_background_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFinancialRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FinancialRole')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User_Profile')),
            ],
        ),
        migrations.AddField(
            model_name='user_profile',
            name='user_financial_role',
            field=models.ManyToManyField(blank=True, through='core.UserFinancialRole', to='core.FinancialRole'),
        ),
    ]
