# Generated by Django 2.2.5 on 2020-03-09 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_auto_20200305_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='user_financial_role',
        ),
        migrations.CreateModel(
            name='UserRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='core.User_Profile')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='core.User_Profile')),
            ],
        ),
        migrations.AddField(
            model_name='user_profile',
            name='user_relationship',
            field=models.ManyToManyField(blank=True, through='core.UserRelationship', to='core.User_Profile'),
        ),
    ]
