# Generated by Django 2.2.5 on 2020-03-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_auto_20200308_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='active_notification_url',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
