# Generated by Django 2.2.5 on 2020-03-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_user_profile_active_notification_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
