# Generated by Django 2.2.5 on 2020-03-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_user_profile_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='zoom_access_token',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='zoom_account_linked',
            field=models.BooleanField(default=False),
        ),
    ]
