# Generated by Django 2.2.5 on 2020-03-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_auto_20200327_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='zoom_refresh_token',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
