# Generated by Django 2.2.5 on 2020-03-29 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_user_profile_zoom_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='zoom_access_token_exp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
