# Generated by Django 2.2.5 on 2020-04-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_user_profile_zoom_access_token_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='gengroup',
            name='zoom_meeting_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='gengroup',
            name='zoom_password',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
