# Generated by Django 2.2.5 on 2020-04-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_gengroup_zoom_active_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='gengroup',
            name='zoom_join_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
