# Generated by Django 2.2.5 on 2020-04-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_gengroup_zoom_join_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gengroup',
            name='zoom_start_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
